# serverless.yml

service: myservice

provider:
  name: aws
  runtime: go1.x

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  echo-lamda:
    handler: bin/echo-lamda
    events:
      - http:
          path: /
          method: any